name: drink_n_talk
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  circular_countdown_timer: ^0.2.0
  cloud_firestore: ^2.5.3
  confetti: ^0.6.0
  cupertino_icons: ^1.0.2
  firebase_core: ^1.6.0
  flutter:
    sdk: flutter
  flutter_screen_wake: ^1.0.2
  flutter_svg: ^0.22.0
  modal_bottom_sheet: ^2.0.0
  qr_code_scanner: ^0.5.2
  qr_flutter: ^4.0.0
  shared_preferences: ^2.0.8

dev_dependencies:
  change_app_package_name: ^1.0.0
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.svg
    - assets/images/end.svg

  fonts:
    - family: Baruta
      fonts:
        - asset: assets/fonts/baruta.ttf
    - family: GothamRounded
      fonts:
        - asset: assets/fonts/GothamRounded.otf
        - asset: assets/fonts/GothamRounded-Bold.otf
          weight: 700
